/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.8.19;

contract Target {
    function foo(uint x) public pure {}

    function foo(uint x, uint y) public payable {}
}

/// #invariant true;
contract Caller {
    struct vars1 {
        bool __scribble_check_invs_at_end;
    }

    function main(Target t) public {
        vars1 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__39.isInContract();
        __ScribbleUtilsLib__39.setInContract(true);
        _original_Caller_main(t);
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__39.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Caller_main(Target t) private {
        t.foo(1);
        _callsite_34(t, 2, 3);
    }

    /// Check only the current contract's state invariants
    function __scribble_Caller_check_state_invariants_internal() internal {
        unchecked {
            if (!(true)) {
                emit __ScribbleUtilsLib__39.AssertionFailed("001076:0066:000 0: ");
                assert(false);
            }
        }
    }

    /// Check the state invariant for the current contract and all its bases
    function __scribble_check_state_invariants() virtual internal {
        __scribble_Caller_check_state_invariants_internal();
    }

    constructor() {
        __ScribbleUtilsLib__39.setInContract(true);
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__39.setInContract(false);
    }

    function _callsite_34(Target receiver, uint256 arg0, uint256 arg1) private {
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__39.setInContract(false);
        receiver.foo(arg0, arg1);
        __ScribbleUtilsLib__39.setInContract(true);
    }
}

library __ScribbleUtilsLib__39 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}
