/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.6.10;

interface IFoo {
    function boo() external;
}

library SillyMath {
    function add(int a, int b) public returns (int) {
        return a + b;
    }
}

library __ScribbleUtilsLib__64 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}

/// #invariant {:msg ""} x>0;
contract Foo is IFoo {
    using SillyMath for int;

    struct vars2 {
        bool __scribble_check_invs_at_end;
    }

    struct vars3 {
        bool __scribble_check_invs_at_end;
    }

    int internal x = 1;

    function boo() override external {
        __ScribbleUtilsLib__64.setInContract(true);
        _original_Foo_boo();
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__64.setInContract(false);
    }

    function _original_Foo_boo() private {}

    function inc() public {
        vars2 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__64.isInContract();
        __ScribbleUtilsLib__64.setInContract(true);
        _original_Foo_inc();
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__64.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_inc() private {
        x++;
    }

    function add(int v) internal {
        x = x.add(v);
    }

    function fail() public {
        vars3 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__64.isInContract();
        __ScribbleUtilsLib__64.setInContract(true);
        _original_Foo_fail();
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__64.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_fail() private {
        add(0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff);
    }

    /// Check only the current contract's state invariants
    function __scribble_Foo_check_state_invariants_internal() internal {
        if (!(x > 0)) {
            __ScribbleUtilsLib__64.assertionFailed("0: ");
            assert(false);
        }
    }

    /// Check the state invariant for the current contract and all its bases
    function __scribble_check_state_invariants() virtual internal {
        __scribble_Foo_check_state_invariants_internal();
    }

    constructor() public {
        __ScribbleUtilsLib__64.setInContract(true);
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__64.setInContract(false);
    }
}
