/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.6.10;

/// #invariant {:msg ""} x>0;
contract Foo {
    struct vars1 {
        bool __scribble_check_invs_at_end;
    }

    struct vars2 {
        bool __scribble_check_invs_at_end;
    }

    int internal x = 1;

    function inc() public {
        vars1 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__32.isInContract();
        __ScribbleUtilsLib__32.setInContract(true);
        _original_Foo_inc();
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__32.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_inc() internal {
        x++;
    }

    function add(int v) internal {
        x += v;
    }

    function fail() public {
        vars2 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__32.isInContract();
        __ScribbleUtilsLib__32.setInContract(true);
        _original_Foo_fail();
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__32.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_fail() internal {
        add(0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff);
    }

    /// Check only the current contract's state invariants
    function __scribble_Foo_check_state_invariants_internal() internal {
        if (!(x > 0)) {
            emit __ScribbleUtilsLib__32.AssertionFailedData(0, abi.encode(x));
            emit __ScribbleUtilsLib__32.AssertionFailed("001629:0066:000 0: ");
        }
    }

    /// Check the state invariant for the current contract and all its bases
    function __scribble_check_state_invariants() virtual internal {
        __scribble_Foo_check_state_invariants_internal();
    }

    constructor() public {
        __ScribbleUtilsLib__32.setInContract(true);
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__32.setInContract(false);
    }
}

library __ScribbleUtilsLib__32 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}
