/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.7.5;

uint constant SOME = 10;

function addSome(uint v) pure returns (uint) {
    return v + SOME;
}

/// Utility contract holding a stack counter
contract __scribble_ReentrancyUtils {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    bool __scribble_out_of_contract = true;
}

contract Test is __scribble_ReentrancyUtils {
    uint internal num;

    function operate() public {
        _original_Test_operate();
        if (!(num == 25)) {
            emit AssertionFailed("0: P1");
            assert(false);
        }
    }

    function _original_Test_operate() private {
        num = addSome(15);
    }
}
