/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.8.11;

/// Utility contract holding a stack counter
contract __scribble_ReentrancyUtils {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    bool __scribble_out_of_contract = true;
}

contract IfSucceedsOnStatement is __scribble_ReentrancyUtils {
    struct vars0 {
        uint256 old_0;
    }

    struct vars1 {
        uint256 old_1;
    }

    function foo(uint amount) public {
        vars0 memory _v;
        uint[] memory a;
        for (uint i = 0; i < a.length; i++) {
            unchecked {
                _v.old_0 = a[i];
            }
            a[i] += amount;
            unchecked {
                if (!((_v.old_0 + amount) == a[i])) {
                    emit AssertionFailed("0: ");
                    assert(false);
                }
            }
        }
    }

    function boo(uint amount) public {
        vars1 memory _v;
        uint[] memory a;
        for (uint i = 0; i < a.length; i++) {
            unchecked {
                _v.old_1 = a[i];
            }
            {
                a[i] += amount;
            }
            unchecked {
                if (!((_v.old_1 + amount) == a[i])) {
                    emit AssertionFailed("1: ");
                    assert(false);
                }
            }
        }
    }
}
