/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.5.17;

contract PointerSwap {
    struct vars0 {
        uint256[] tuple_tmp_0;
        uint256[] tuple_tmp_1;
    }

    uint[] internal a = [1, 2, 3];
    uint[] internal b = [4, 5, 6];

    function main() public {
        vars0 memory _v;
        (_v.tuple_tmp_1, _v.tuple_tmp_0) = (b, a);
        b = _v.tuple_tmp_0;
        PointerSwap_a_ptr_arr_uint256_memory_assign(_v.tuple_tmp_1);
        assert((a[0] == 4) && (b[0] == 1));
    }

    function PointerSwap_a_inline_initializer() internal {
        if (!(true)) {
            __ScribbleUtilsLib__43.assertionFailed("000676:0061:000 0: ");
            assert(false);
        }
    }

    constructor() public {
        PointerSwap_a_inline_initializer();
    }

    function PointerSwap_a_ptr_arr_uint256_memory_assign(uint256[] memory ARG0) internal returns (uint256[] storage RET0) {
        a = ARG0;
        RET0 = a;
        if (!(true)) {
            __ScribbleUtilsLib__43.assertionFailed("001056:0061:000 0: ");
            assert(false);
        }
    }
}

library __ScribbleUtilsLib__43 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}
