/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.8.21;

/// #if_succeeds x == 5;
contract Example01 {
    uint private x;

    constructor() {
        _original_Example01_constructor();
        unchecked {
            if (!(x == 5)) {
                emit __ScribbleUtilsLib__49.AssertionFailed("000342:0066:000 0: ");
                assert(false);
            }
        }
    }

    function _original_Example01_constructor() private {
        x = 5;
    }
}

contract Example02 {
    uint private x;

    constructor() {
        _original_Example02_constructor();
        unchecked {
            if (!(x == 5)) {
                emit __ScribbleUtilsLib__49.AssertionFailed("000723:0066:000 1: ");
                assert(false);
            }
        }
    }

    function _original_Example02_constructor() private {
        x = 5;
    }
}

/// #require x == 5;
contract Example03 {
    uint private x;

    constructor() {
        unchecked {
            require(x == 5);
        }
        _original_Example03_constructor();
    }

    function _original_Example03_constructor() private {
        x = 5;
    }
}

contract Example04 {
    uint private x;

    constructor() {
        unchecked {
            require(x == 5);
        }
        _original_Example04_constructor();
    }

    function _original_Example04_constructor() private {
        x = 5;
    }
}

library __ScribbleUtilsLib__49 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}
