/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.6.10;

/// #invariant {:msg ""} x > 0;
contract Foo {
    struct vars1 {
        bool __scribble_check_invs_at_end;
    }

    struct vars2 {
        bool __scribble_check_invs_at_end;
    }

    uint internal x = 1;

    function getX() public returns (uint RET_0) {
        vars1 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__39.isInContract();
        __ScribbleUtilsLib__39.setInContract(true);
        RET_0 = _original_Foo_getX();
        if (!(x > 0)) {
            emit __ScribbleUtilsLib__39.AssertionFailed("00641:063:00 1: ");
            assert(false);
        }
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__39.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_getX() private view returns (uint) {
        return x;
    }

    function getXPlus1() public returns (uint) {
        return getX() + 1;
    }

    function getXPlus2() public returns (uint RET_0) {
        vars2 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__39.isInContract();
        __ScribbleUtilsLib__39.setInContract(true);
        RET_0 = _original_Foo_getXPlus2();
        if (!(x > 2)) {
            emit __ScribbleUtilsLib__39.AssertionFailed("01377:063:00 2: ");
            assert(false);
        }
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__39.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_getXPlus2() private returns (uint) {
        return getXPlus1() + 1;
    }

    /// Check only the current contract's state invariants
    function __scribble_Foo_check_state_invariants_internal() internal {
        if (!(x > 0)) {
            emit __ScribbleUtilsLib__39.AssertionFailed("01919:063:00 0: ");
            assert(false);
        }
    }

    /// Check the state invariant for the current contract and all its bases
    function __scribble_check_state_invariants() virtual internal {
        __scribble_Foo_check_state_invariants_internal();
    }

    constructor() public {
        __ScribbleUtilsLib__39.setInContract(true);
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__39.setInContract(false);
    }
}

library __ScribbleUtilsLib__39 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}
