/// This file is auto-generated by Scribble and shouldn't be edited directly.
/// Use --disarm prior to make any changes.
pragma solidity 0.8.25;

///  😀😀😀😀😀😀😀
///  #invariant "😀😀😀😀😀😀😀" true;
contract Foo {
    struct vars1 {
        bool __scribble_check_invs_at_end;
    }

    function main() public {
        vars1 memory _v;
        _v.__scribble_check_invs_at_end = !__ScribbleUtilsLib__8.isInContract();
        __ScribbleUtilsLib__8.setInContract(true);
        _original_Foo_main();
        unchecked {
            if (!(true)) {
                emit __ScribbleUtilsLib__8.AssertionFailed(unicode"000597:0100:000 1: 😀😀😀😀😀😀😀");
                assert(false);
            }
        }
        if (_v.__scribble_check_invs_at_end) __scribble_check_state_invariants();
        __ScribbleUtilsLib__8.setInContract(!_v.__scribble_check_invs_at_end);
    }

    function _original_Foo_main() internal {}

    /// Check only the current contract's state invariants
    function __scribble_Foo_check_state_invariants_internal() internal {
        unchecked {
            if (!(true)) {
                emit __ScribbleUtilsLib__8.AssertionFailed(unicode"001164:0100:000 0: 😀😀😀😀😀😀😀");
                assert(false);
            }
        }
    }

    /// Check the state invariant for the current contract and all its bases
    function __scribble_check_state_invariants() virtual internal {
        __scribble_Foo_check_state_invariants_internal();
    }

    constructor() {
        __ScribbleUtilsLib__8.setInContract(true);
        __scribble_check_state_invariants();
        __ScribbleUtilsLib__8.setInContract(false);
    }
}

library __ScribbleUtilsLib__8 {
    event AssertionFailed(string message);

    event AssertionFailedData(int eventId, bytes encodingData);

    function assertionFailed(string memory arg_0) internal {
        emit AssertionFailed(arg_0);
    }

    function assertionFailedData(int arg_0, bytes memory arg_1) internal {
        emit AssertionFailedData(arg_0, arg_1);
    }

    function isInContract() internal returns (bool res) {
        assembly {
            res := sload(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c)
        }
    }

    function setInContract(bool v) internal {
        assembly {
            sstore(0x5f0b92cf9616afdee4f4136f66393f1343b027f01be893fa569eb2e2b667a40c, v)
        }
    }
}
